### PR TITLE
Add support for differing indexing algorithms

### PR DESCRIPTION
**Pull request by emilbayes**
Adds support for changing indexing strategy (eg btree to brin)

### CODE REVIEW

**Comment by djrobstep** [comment]
Hey, thanks heaps for this PR. This looks good! 

It currently breaks a test however - do you want to fix this up, or would you prefer I do that? Once that's sorted we can roll this out.

**Comment by emilbayes** [comment]
I can’t seem to see the CircleCI outputs, do I need some kind of permission? If it’s an easy change you can do it but if it’s more work I’m happy to ease your burden :)

**Comment by emilbayes** [comment]
Wrt changing behaviour, for algorithm change only I change it by hand to a `CREATE INDEX CONCURRENTLY $NAME_diff ...; DROP INDEX $NAME; ALTER INDEX ... RENAME TO ...;`. I don’t know if that kind of sophisticated output is something that would be possible in the future? Right now it gathers all drops and then creates later

**Comment by djrobstep** [comment]
Hmm, might be a permissions thing. I'll fix it up.

**Comment by djrobstep** [comment]
Creating with a different name and then renaming would be a great addition. Definitely something we can add in the future.

**Pull request merged**
