### PR TITLE
Use definition to compare indices, if available

### PR DESCRIPTION
**Pull request by akeeman**

### CODE REVIEW

**Comment by djrobstep** [comment]
Thanks so much for this PR.. Is it possible you can add a test that demonstrates what this fixes?

**Comment by akeeman** [comment]
Sure. It will take me several weeks, though.

**Comment by kwargs** [comment]
There is another solution.
We can fix query, that get indexes.

https://www.postgresql.org/docs/11/interactive/catalog-pg-index.html
`indexprs` and `indpred` are 'internal' representation. We just need convert it to text.
```
diff --git a/schemainspect/pg/sql/indexes.sql b/schemainspect/pg/sql/indexes.sql
index ea87c73..57d7e5d 100644
--- a/schemainspect/pg/sql/indexes.sql
+++ b/schemainspect/pg/sql/indexes.sql
@@ -15,7 +15,8 @@ with extension_oids as (
        indoption key_options, indnatts num_att, indisunique is_unique,
        indisprimary is_pk, indisexclusion is_exclusion, indimmediate is_immediate,
        indisclustered is_clustered, indcollation key_collations,
-       indexprs key_expressions, indpred partial_predicate
+       pg_get_expr(indexprs, indrelid) key_expressions,
+       pg_get_expr(indpred, indrelid) partial_predicate
   FROM pg_index x
     JOIN pg_class c ON c.oid = x.indrelid
     JOIN pg_class i ON i.oid = x.indexrelid
```

**Comment by akeeman** [comment]
Looks good. Let me look into it.

**Comment by djrobstep** [comment]
@akeeman i've just merged a PR from @kwargs  that addresses this. hopefully that resolves this issue for you. i'll close this for now, please reopen if you encounter any further trouble

**Pull request closed without merging**
